file.open("imp.lua",'w')
file.writeline([[ssid = "Gx2_4189"]])
file.writeline([[password = "taeugi323"  -- Hotspot ID and password]])
file.writeline([[host = '61.37.62.236']])
file.writeline([[path = "/transmit?"     -- url format. Server is a node.js virtual web server.]])
file.writeline([[ready = false]])
file.writeline([[]])
file.writeline([[uart.setup(0, 9600, 8, 0, 1, 0)]])
file.writeline([[uart.on("data", "\n", function(data)]])
file.writeline([[  data = string.gsub(data, "[\r\n]", " ")]])
file.writeline([[  call_server(data)]])
file.writeline([[end, 0)  ]])
file.writeline([[]])
file.writeline([[wifi.setmode(wifi.STATION)]])
file.writeline([[wifi.sta.config(ssid, password)]])
file.writeline([[wifi.sta.autoconnect(1)]])
file.writeline([[]])
file.writeline([[--serial = 0]])
file.writeline([[cnt = 1]])
file.writeline([[tmr.alarm(3, 3000, 1, function() ]])
file.writeline([[  if (wifi.sta.getip() == nil) and (cnt < 20) then ]])
file.writeline([[    print("trying wifi AP..."..cnt.." sec")]])
file.writeline([[    cnt = cnt + 1 ]])
file.writeline([[  else ]])
file.writeline([[    tmr.stop(3)]])
file.writeline([[    if (cnt < 20) then ]])
file.writeline([[      ip = wifi.sta.getip();]])
file.writeline([[      print("got wifi="..ip..", status="..wifi.sta.status());]])
file.writeline([[      ready = true]])
file.writeline([[    else node.restart()]])
file.writeline([[    end]])
file.writeline([[    cnt = nil;]])
file.writeline([[  end]])
file.writeline([[end)]])
file.writeline([[  ]])
file.writeline([[function call_server(value)]])
file.writeline([[]])
file.writeline([[  if ready == false then return end]])
file.writeline([[  ]])
file.writeline([[  conn=net.createConnection(net.TCP, 0) ]])
file.writeline([[  conn:connect(2232, host) ]])
file.writeline([[  print("[pre_connection] OK ")]])
file.writeline([[  conn:on("connection",function(conn, payload)]])
file.writeline([[    print("[connection] "..path..value)]])
file.writeline([[    conn:send("GET "..path..value.." HTTP/1.1\r\n"..]])
file.writeline([[      "Host: "..host.."\r\n"..]])
file.writeline([[      "Connection: keep-alive\r\n"..]])
file.writeline([[      "Accept: */*\r\n"..]])
file.writeline([[      "User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36\r\n"..]])
file.writeline([[      "\r\n") ]])
file.writeline([[    print("[connection] Finished")]])
file.writeline([[  end) ]])
file.writeline([[  ]])
file.writeline([[  conn:on("receive", function(conn, payload) ]])
file.writeline([[    print("[receive] "..payload)]])
file.writeline([[    conn:close();]])
file.writeline([[  end)]])
file.writeline([[    ]])
file.writeline([[end]])
file.writeline([[]])
file.writeline([[]])
file.close()